# Generated by Django 6.0.5 on 2026-05-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='cta_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
