# Generated by Django 6.0.5 on 2026-05-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_heroslide_cta_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='features',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='price',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='show_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_url',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
