# Generated by Django 6.0.5 on 2026-05-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_heroslide_features_remove_heroslide_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCard',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='cta_url',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='show_title',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='title',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
