# Generated by Django 6.0.5 on 2026-05-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_promocard_remove_heroslide_cta_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
