# Generated by Django 6.0.5 on 2026-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_category_image_category_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default=1, upload_to='brands/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brand',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
