# Generated by Django 6.0.5 on 2026-05-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_brand_options_brand_is_active_brand_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
