# Generated by Django 4.2.26 on 2026-05-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_product_brand_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_zone_background', models.ImageField(blank=True, help_text='Background image behind hero sliders and brand strip (up to Popular Categories).', null=True, upload_to='home/backgrounds/')),
            ],
            options={
                'verbose_name': 'Homepage settings',
                'verbose_name_plural': 'Homepage settings',
            },
        ),
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['placement', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='heroslide',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video file')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='placement',
            field=models.CharField(choices=[('left', 'Left slider'), ('right', 'Right slider')], default='left', help_text='Which hero slider this slide appears in.', max_length=10),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='video',
            field=models.FileField(blank=True, help_text='MP4/WebM video file (used when media type is Video).', null=True, upload_to='hero/videos/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
