# Generated by Django 4.2.26 on 2026-05-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_hero_placement_video_and_home_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Global Link Store', max_length=255)),
                ('heading', models.CharField(default='Quality laptops, phones & electronics — delivered across Nepal', max_length=255)),
                ('description', models.TextField(default='Global Link Store is your trusted online destination for laptops, smartphones, desktops, and accessories. We partner with leading brands and focus on genuine products, fair pricing, and reliable support.')),
                ('products_listed', models.PositiveIntegerField(default=500, help_text='Shown in stats counter (e.g. products available).')),
                ('orders_delivered', models.PositiveIntegerField(default=1200, help_text='Shown in stats counter.')),
                ('happy_customers', models.PositiveIntegerField(default=850, help_text='Shown in stats counter.')),
                ('years_of_service', models.PositiveIntegerField(default=5, help_text='Years in business — counter animates to this number.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About section',
                'verbose_name_plural': 'About section',
            },
        ),
    ]
