# Generated by Django 6.0.5 on 2026-06-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_newslettersubscriber_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('right_top', 'Right — Top (large)'), ('right_bottom', 'Right — Bottom (small, max 2)')], default='right_top', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('cta_label', models.CharField(blank=True, default='', help_text="Button text e.g. 'Buy Now'. Leave blank to hide button.", max_length=60)),
                ('link', models.CharField(blank=True, default='#', help_text='URL the entire banner card links to.', max_length=255)),
                ('background', models.ImageField(blank=True, help_text='Full-bleed background image for the card.', null=True, upload_to='hero/banners/bg/')),
                ('image', models.ImageField(blank=True, help_text='Product / subject image shown on the right side of the card.', null=True, upload_to='hero/banners/img/')),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower = shown first.')),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['placement', 'order', 'id'],
            },
        ),
    ]
