# Generated by Django 6.0.5 on 2026-05-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
    ]
