# Generated by Django 6.0.5 on 2026-05-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_inventory_and_key_specs'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariantstock',
            name='unique_product_variant_note_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='productvariantoption',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ProductVariantStock',
        ),
    ]
