# Generated by Django 6.0.5 on 2026-05-25 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productvariantstock_unique_product_variant_note_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_combo', models.CharField(blank=True, help_text='Comma-separated key:value pairs. e.g. "Color:Black,Storage:128GB"', max_length=255)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.product')),
            ],
            options={
                'ordering': ['variant_combo'],
                'unique_together': {('product', 'variant_combo')},
            },
        ),
    ]
