# Generated by Django 6.0.5 on 2026-05-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_stock_productsku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantoption',
            name='price_adjustment',
        ),
    ]
