# Generated by Django 6.0.5 on 2026-05-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productvariantoption_price_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='variant_combo',
            field=models.CharField(blank=True, help_text='Comma-separated key:value pairs. e.g. "Color:Black,Variant:8GB+128GB"', max_length=255),
        ),
    ]
